export const deliveryConfig = Object.freeze({
  storeAddress:
    'Rua Monsenhor Costa Rego, Cohab São Francisco, Petrolina-PE, CEP 56309-440',
  calculationMode: 'fixed-zones',
  externalRouting: Object.freeze({
    enabled: false,
    provider: null,
  }),
})

export const deliveryZones = Object.freeze([
  { neighborhood: 'Cohab São Francisco / Cohab VI', distanceKm: 2, aliases: ['cohab 6', 'cohab vi', 'cohab são francisco', 'cohab sao francisco'] },
  { neighborhood: 'Rio Corrente', distanceKm: 3 },
  { neighborhood: 'Rio Claro', distanceKm: 3 },
  { neighborhood: 'São Gonçalo', distanceKm: 3 },
  { neighborhood: 'Cohab Massangano', distanceKm: 4 },
  { neighborhood: 'Jardim Guararapes', distanceKm: 4 },
  { neighborhood: 'Jardim Petrópolis', distanceKm: 4 },
  { neighborhood: 'Jardim Amazonas', distanceKm: 5 },
  { neighborhood: 'Jardim Maravilha', distanceKm: 5 },
  { neighborhood: 'Pedro Raimundo', distanceKm: 5 },
  { neighborhood: 'Areia Branca', distanceKm: 6 },
  { neighborhood: 'São José', distanceKm: 6 },
  { neighborhood: 'Maria Auxiliadora', distanceKm: 6 },
  { neighborhood: 'Gercino Coelho', distanceKm: 6 },
  { neighborhood: 'Centro', distanceKm: 7 },
  { neighborhood: 'Atrás da Banca', distanceKm: 7 },
  { neighborhood: 'Vila Eduardo', distanceKm: 7 },
  { neighborhood: 'Vila Mocó', distanceKm: 7 },
  { neighborhood: 'Palhinhas', distanceKm: 7 },
  { neighborhood: 'KM-2', distanceKm: 7 },
  { neighborhood: 'Ouro Preto', distanceKm: 8 },
  { neighborhood: 'Alto do Cocar', distanceKm: 8 },
  { neighborhood: 'Caminho do Sol', distanceKm: 8 },
  { neighborhood: 'Dom Malan', distanceKm: 8 },
  { neighborhood: 'Jardim São Paulo', distanceKm: 8 },
  { neighborhood: 'José e Maria', distanceKm: 9 },
  { neighborhood: 'Cosme e Damião', distanceKm: 9 },
  { neighborhood: 'Dom Avelar', distanceKm: 10 },
  { neighborhood: 'Antonio Cassimiro', distanceKm: 10, aliases: ['antônio cassimiro'] },
  { neighborhood: 'João de Deus', distanceKm: 11 },
  { neighborhood: 'Topázio', distanceKm: 11 },
  { neighborhood: 'Pedra Linda', distanceKm: 11 },
  { neighborhood: 'Portal da Cidade', distanceKm: 12 },
  { neighborhood: 'Pedra do Bode', distanceKm: 12 },
  { neighborhood: 'Cidade Universitária', distanceKm: 13 },
  { neighborhood: 'Loteamento Recife', distanceKm: 13 },
  { neighborhood: 'Jatobá', distanceKm: 14 },
  { neighborhood: 'Henrique Leite', distanceKm: 14 },
  { neighborhood: 'Distrito Industrial', distanceKm: 15 },
  { neighborhood: 'Colônia Imperial', distanceKm: 16 },
  { neighborhood: 'Terra do Sul', distanceKm: 16 },
  { neighborhood: 'Vale Grande Rio', distanceKm: 17 },
  { neighborhood: 'Vila Eulália', distanceKm: 17 },
  { neighborhood: 'Vila dos Ingás II', distanceKm: 18 },
])
