export const storeConfig = {
  name: 'Encanto do Vale',
  logoUrl: 'https://i.ibb.co/Xf8btGBN/IMG-2444.png',
  tagline: 'Cardápio digital artesanal',
  whatsappPhone: '5587988028002',
  instagramUrl: 'https://instagram.com/doceria.encantodovale',
  email: 'encantodovale986@gmail.com',
  city: 'Petrolina - PE',
  serviceSummary: 'Encomendas, pronta entrega e delivery sob consulta',
  orderHours: 'Pedidos: 9h às 19h',
  weeklyHours: [
    { day: 0, label: 'Dom', open: '09:00', close: '19:00', closed: false },
    { day: 1, label: 'Seg', open: '09:00', close: '19:00', closed: false },
    { day: 2, label: 'Ter', open: '09:00', close: '19:00', closed: false },
    { day: 3, label: 'Qua', open: '09:00', close: '19:00', closed: false },
    { day: 4, label: 'Qui', open: '09:00', close: '19:00', closed: false },
    { day: 5, label: 'Sex', open: '09:00', close: '19:00', closed: false },
    { day: 6, label: 'Sab', open: '09:00', close: '19:00', closed: false },
  ],
  defaultDeliveryFee: 10,
}
